// src/frontend/vue/src/App.vue
<script setup>
import { computed, onMounted, ref } from 'vue'

const authStorageKey = 'online-store-auth-vue'
const loginEmail = ref('demo@example.com')
const loginPassword = ref('demo-password')
const registerEmail = ref('')
const registerPassword = ref('')
const registerFullName = ref('')
const loginBusy = ref(false)
const registerBusy = ref(false)
const loginMessage = ref(null)
const registerMessage = ref(null)
const authToken = ref(null)
const refreshToken = ref(null)
const currentUser = ref(null)

const products = ref([])
const cart = ref([])
const loading = ref(true)
const error = ref(null)
const checkoutResult = ref(null)
const checkoutBusy = ref(false)

const isAuthenticated = computed(() => !!authToken.value && !!currentUser.value)

const cartSummary = computed(() =>
  cart.value.reduce((sum, item) => sum + item.quantity * item.unitPrice, 0),
)

function formatPrice(value) {
  return value.toFixed(2)
}

function newIdempotencyKey() {
  if (typeof crypto !== 'undefined' && 'randomUUID' in crypto) {
    return crypto.randomUUID()
  }
  return `checkout-${Date.now()}`
}

async function loadProducts() {
  loading.value = true
  error.value = null
  try {
    const res = await fetch('/api/products')
    if (!res.ok) {
      throw new Error(`Products failed: ${res.status}`)
    }
    products.value = await res.json()
  } catch (e) {
    error.value = e instanceof Error ? e.message : 'Failed to load products'
  } finally {
    loading.value = false
  }
}

async function persistCart(items) {
  if (!currentUser.value?.userId) {
    throw new Error('Please login first.')
  }
  const res = await authenticatedFetch(`/api/carts/${currentUser.value.userId}`, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ userId: currentUser.value.userId, items }),
  })
  if (!res.ok) {
    throw new Error(`Cart save failed: ${res.status}`)
  }
}

async function addToCart(product) {
  error.value = null
  if (!currentUser.value?.userId) {
    error.value = 'Please login first.'
    return
  }
  const next = [...cart.value]
  const existing = next.find((x) => x.productId === product.productId)
  if (existing) {
    existing.quantity += 1
  } else {
    next.push({ productId: product.productId, quantity: 1, unitPrice: product.price })
  }

  try {
    await persistCart(next)
    cart.value = next
  } catch (e) {
    error.value = e instanceof Error ? e.message : 'Cart error'
  }
}

async function checkout() {
  checkoutBusy.value = true
  checkoutResult.value = null
  error.value = null
  try {
    if (!currentUser.value?.userId || !authToken.value) {
      throw new Error('Please login first.')
    }

    if (cart.value.length === 0) {
      throw new Error('Cart is empty. Add a product first.')
    }

    const res = await authenticatedFetch('/api/checkout', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Idempotency-Key': newIdempotencyKey(),
      },
      body: JSON.stringify({
        userId: currentUser.value.userId,
        currency: 'USD',
        items: cart.value.map((c) => ({
          productId: c.productId,
          quantity: c.quantity,
          unitPrice: c.unitPrice,
        })),
      }),
    })

    const body = await res.json().catch(() => ({}))
    if (!res.ok) {
      throw new Error(body?.error || `Checkout failed: ${res.status}`)
    }

    checkoutResult.value = body
    cart.value = []
    await loadProducts()
  } catch (e) {
    error.value = e instanceof Error ? e.message : 'Checkout error'
  } finally {
    checkoutBusy.value = false
  }
}

function persistAuthSession(token, nextRefreshToken, user) {
  localStorage.setItem(
    authStorageKey,
    JSON.stringify({
      accessToken: token,
      refreshToken: nextRefreshToken,
      user,
    }),
  )
}

function restoreAuthSession() {
  try {
    const raw = localStorage.getItem(authStorageKey)
    if (!raw) {
      return
    }
    const parsed = JSON.parse(raw)
    if (parsed?.accessToken && parsed?.refreshToken && parsed?.user?.userId) {
      authToken.value = parsed.accessToken
      refreshToken.value = parsed.refreshToken
      currentUser.value = parsed.user
      loginEmail.value = parsed.user.email
    }
  } catch {
    localStorage.removeItem(authStorageKey)
  }
}

async function tryRefreshToken() {
  if (!refreshToken.value) {
    return null
  }

  const res = await fetch('/api/users/refresh', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ refreshToken: refreshToken.value }),
  })
  const body = await res.json().catch(() => ({}))
  if (!res.ok || !body?.accessToken || !body?.refreshToken || !body?.user?.userId) {
    return null
  }

  authToken.value = body.accessToken
  refreshToken.value = body.refreshToken
  currentUser.value = body.user
  persistAuthSession(body.accessToken, body.refreshToken, body.user)
  return body.accessToken
}

async function authenticatedFetch(url, init = {}) {
  const headers = new Headers(init.headers || {})
  if (authToken.value && !headers.has('Authorization')) {
    headers.set('Authorization', `Bearer ${authToken.value}`)
  }

  let response = await fetch(url, { ...init, headers })
  if (response.status !== 401) {
    return response
  }

  const refreshedAccessToken = await tryRefreshToken()
  if (!refreshedAccessToken) {
    return response
  }

  const retryHeaders = new Headers(init.headers || {})
  if (!retryHeaders.has('Authorization')) {
    retryHeaders.set('Authorization', `Bearer ${refreshedAccessToken}`)
  }
  response = await fetch(url, { ...init, headers: retryHeaders })
  return response
}

async function login() {
  loginBusy.value = true
  loginMessage.value = null
  try {
    const res = await fetch('/api/users/login', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email: loginEmail.value.trim(), password: loginPassword.value }),
    })
    const body = await res.json().catch(() => ({}))
    if (!res.ok || !body?.accessToken || !body?.refreshToken || !body?.user?.userId) {
      throw new Error(body?.error || 'Invalid login credentials.')
    }
    authToken.value = body.accessToken
    refreshToken.value = body.refreshToken
    currentUser.value = body.user
    persistAuthSession(body.accessToken, body.refreshToken, body.user)
    loginMessage.value = `Logged in as ${body.user.fullName}`
    cart.value = []
  } catch (e) {
    loginMessage.value = e instanceof Error ? e.message : 'Login failed'
  } finally {
    loginBusy.value = false
  }
}

async function register() {
  registerBusy.value = true
  registerMessage.value = null
  try {
    const res = await fetch('/api/users/register', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        email: registerEmail.value.trim(),
        password: registerPassword.value,
        fullName: registerFullName.value.trim(),
      }),
    })
    const body = await res.json().catch(() => ({}))
    if (!res.ok || !body?.userId) {
      throw new Error(body?.error || 'Registration failed.')
    }
    registerMessage.value = 'Registration successful. You can now login.'
    loginEmail.value = registerEmail.value.trim()
    loginPassword.value = registerPassword.value
    registerEmail.value = ''
    registerPassword.value = ''
    registerFullName.value = ''
  } catch (e) {
    registerMessage.value = e instanceof Error ? e.message : 'Registration failed'
  } finally {
    registerBusy.value = false
  }
}

function logout() {
  if (refreshToken.value) {
    void fetch('/api/users/logout', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ refreshToken: refreshToken.value }),
    })
  }
  authToken.value = null
  refreshToken.value = null
  currentUser.value = null
  cart.value = []
  loginMessage.value = 'Logged out.'
  localStorage.removeItem(authStorageKey)
}

onMounted(async () => {
  restoreAuthSession()
  await loadProducts()
})
</script>

<template>
  <main>
    <h1>Online Store (Vue - Gateway)</h1>
    <p class="subtitle">
      Demo user is pre-seeded in UserService. Cart is stored via CartService through the gateway.
    </p>

    <p v-if="error" class="error">{{ error }}</p>

    <section>
      <h2>Login</h2>
      <p v-if="loginMessage" class="message">{{ loginMessage }}</p>
      <form class="login-form" @submit.prevent="login">
        <label>
          Email
          <input v-model="loginEmail" type="email" required />
        </label>
        <label>
          Password
          <input v-model="loginPassword" type="password" required />
        </label>
        <div class="row-actions">
          <button type="submit" :disabled="loginBusy">
            {{ loginBusy ? 'Logging in...' : 'Login' }}
          </button>
          <button type="button" :disabled="!isAuthenticated" @click="logout">Logout</button>
        </div>
      </form>
      <p v-if="isAuthenticated && currentUser">
        Logged in user: <strong>{{ currentUser.fullName }}</strong> ({{ currentUser.email }})
      </p>
    </section>

    <section>
      <h2>Register</h2>
      <p v-if="registerMessage" class="message">{{ registerMessage }}</p>
      <form class="login-form" @submit.prevent="register">
        <label>
          Full name
          <input v-model="registerFullName" type="text" required />
        </label>
        <label>
          Email
          <input v-model="registerEmail" type="email" required />
        </label>
        <label>
          Password
          <input v-model="registerPassword" type="password" required />
        </label>
        <div class="row-actions">
          <button type="submit" :disabled="registerBusy">
            {{ registerBusy ? 'Registering...' : 'Register' }}
          </button>
        </div>
      </form>
    </section>

    <section>
      <h2>Catalog</h2>
      <p v-if="loading">Loading...</p>
      <ul v-else>
        <li v-for="product in products" :key="product.productId">
          <span>
            <strong>{{ product.name }}</strong> - ${{ formatPrice(product.price) }}
          </span>
          <button type="button" @click="addToCart(product)">Add to cart</button>
        </li>
      </ul>
    </section>

    <section>
      <h2>Cart</h2>
      <p v-if="!isAuthenticated">Login required to persist cart and checkout.</p>
      <p v-if="cart.length === 0">Empty</p>
      <ul v-else>
        <li v-for="item in cart" :key="item.productId">
          <span>{{ item.productId }}</span>
          <span>qty {{ item.quantity }} @ ${{ formatPrice(item.unitPrice) }}</span>
        </li>
      </ul>
      <p><strong>Total:</strong> ${{ formatPrice(cartSummary) }}</p>
      <button type="button" :disabled="checkoutBusy" @click="checkout">
        {{ checkoutBusy ? 'Checking out...' : 'Checkout' }}
      </button>
    </section>

    <section v-if="checkoutResult">
      <h2>Last checkout</h2>
      <pre>{{ JSON.stringify(checkoutResult, null, 2) }}</pre>
    </section>
  </main>
</template>

<style scoped>
main {
  font-family: Inter, Arial, sans-serif;
  max-width: 900px;
  margin: 0 auto;
  padding: 1rem;
}

.subtitle {
  color: #475569;
  margin-top: 0;
}

section {
  border: 1px solid #e2e8f0;
  border-radius: 8px;
  padding: 1rem;
  margin-top: 1rem;
}

ul {
  list-style: none;
  padding-left: 0;
  margin: 0;
}

li {
  display: flex;
  justify-content: space-between;
  gap: 0.75rem;
  padding: 0.5rem 0;
}

button {
  cursor: pointer;
}

.message {
  color: #0f766e;
}

.error {
  color: #b91c1c;
}

pre {
  overflow: auto;
  background: #f8fafc;
  border-radius: 6px;
  padding: 0.75rem;
}

.login-form {
  display: grid;
  gap: 0.75rem;
  margin-bottom: 0.75rem;
}

.login-form label {
  display: grid;
  gap: 0.35rem;
  font-weight: 600;
}

input[type='email'],
input[type='password'],
input[type='text'] {
  border: 1px solid #cbd5e1;
  border-radius: 6px;
  padding: 0.4rem 0.5rem;
}

.row-actions {
  display: flex;
  gap: 0.5rem;
  align-items: center;
}
</style>

// src/frontend/react/src/App.tsx
import { useCallback, useEffect, useMemo, useState } from "react";

type Product = {
  productId: string;
  name: string;
  description: string;
  price: number;
  isActive?: boolean;
};

type CartItem = {
  productId: string;
  quantity: number;
  unitPrice: number;
};

type UserProfile = {
  userId: string;
  email: string;
  fullName: string;
  createdAt: string;
};

type LoginResponse = {
  accessToken: string;
  refreshToken: string;
  accessTokenExpiresAt: string;
  user: UserProfile;
};

const authStorageKey = "online-store-auth-react";

function newIdempotencyKey(): string {
  if (typeof crypto !== "undefined" && "randomUUID" in crypto) {
    return crypto.randomUUID();
  }
  return `checkout-${Date.now()}`;
}

export default function App() {
  const [loginEmail, setLoginEmail] = useState("demo@example.com");
  const [loginPassword, setLoginPassword] = useState("demo-password");
  const [registerEmail, setRegisterEmail] = useState("");
  const [registerPassword, setRegisterPassword] = useState("");
  const [registerFullName, setRegisterFullName] = useState("");
  const [authToken, setAuthToken] = useState<string | null>(null);
  const [refreshToken, setRefreshToken] = useState<string | null>(null);
  const [currentUser, setCurrentUser] = useState<UserProfile | null>(null);
  const [loginBusy, setLoginBusy] = useState(false);
  const [registerBusy, setRegisterBusy] = useState(false);
  const [loginMessage, setLoginMessage] = useState<string | null>(null);
  const [registerMessage, setRegisterMessage] = useState<string | null>(null);
  const [products, setProducts] = useState<Product[]>([]);
  const [cart, setCart] = useState<CartItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [checkoutResult, setCheckoutResult] = useState<unknown>(null);
  const [checkoutBusy, setCheckoutBusy] = useState(false);

  useEffect(() => {
    try {
      const raw = localStorage.getItem(authStorageKey);
      if (!raw) {
        return;
      }
      const parsed = JSON.parse(raw) as { accessToken?: string; refreshToken?: string; user?: UserProfile };
      if (parsed.accessToken && parsed.refreshToken && parsed.user?.userId) {
        setAuthToken(parsed.accessToken);
        setRefreshToken(parsed.refreshToken);
        setCurrentUser(parsed.user);
        setLoginEmail(parsed.user.email);
      }
    } catch {
      localStorage.removeItem(authStorageKey);
    }
  }, []);

  const persistAuth = useCallback((token: string, nextRefreshToken: string, user: UserProfile) => {
    localStorage.setItem(authStorageKey, JSON.stringify({ accessToken: token, refreshToken: nextRefreshToken, user }));
  }, []);

  const logout = useCallback(() => {
    if (refreshToken) {
      void fetch("/api/users/logout", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ refreshToken }),
      });
    }
    setAuthToken(null);
    setRefreshToken(null);
    setCurrentUser(null);
    setCart([]);
    setLoginMessage("Logged out.");
    localStorage.removeItem(authStorageKey);
  }, [refreshToken]);

  const tryRefreshToken = useCallback(async (): Promise<string | null> => {
    if (!refreshToken) {
      return null;
    }

    const res = await fetch("/api/users/refresh", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ refreshToken }),
    });
    const body = (await res.json().catch(() => ({}))) as Partial<LoginResponse>;
    if (!res.ok || !body.accessToken || !body.refreshToken || !body.user?.userId) {
      return null;
    }

    setAuthToken(body.accessToken);
    setRefreshToken(body.refreshToken);
    setCurrentUser(body.user);
    persistAuth(body.accessToken, body.refreshToken, body.user);
    return body.accessToken;
  }, [persistAuth, refreshToken]);

  const authenticatedFetch = useCallback(async (input: RequestInfo | URL, init?: RequestInit): Promise<Response> => {
    const headers = new Headers(init?.headers ?? {});
    if (authToken && !headers.has("Authorization")) {
      headers.set("Authorization", `Bearer ${authToken}`);
    }

    let response = await fetch(input, { ...init, headers });
    if (response.status !== 401) {
      return response;
    }

    const refreshedToken = await tryRefreshToken();
    if (!refreshedToken) {
      return response;
    }

    const retryHeaders = new Headers(init?.headers ?? {});
    if (!retryHeaders.has("Authorization")) {
      retryHeaders.set("Authorization", `Bearer ${refreshedToken}`);
    }
    response = await fetch(input, { ...init, headers: retryHeaders });
    return response;
  }, [authToken, tryRefreshToken]);

  const login = useCallback(async () => {
    setLoginBusy(true);
    setLoginMessage(null);
    setError(null);
    try {
      const res = await fetch("/api/users/login", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email: loginEmail.trim(), password: loginPassword }),
      });

      const body = (await res.json().catch(() => ({}))) as Partial<LoginResponse> & { error?: string };
      if (!res.ok || !body.accessToken || !body.user?.userId) {
        throw new Error(body.error || "Invalid login credentials.");
      }

      setAuthToken(body.accessToken);
      setRefreshToken(body.refreshToken ?? null);
      setCurrentUser(body.user);
      if (body.refreshToken) {
        persistAuth(body.accessToken, body.refreshToken, body.user);
      }
      setLoginMessage(`Logged in as ${body.user.fullName}`);
      setCart([]);
    } catch (e) {
      setLoginMessage(e instanceof Error ? e.message : "Login failed");
    } finally {
      setLoginBusy(false);
    }
  }, [loginEmail, loginPassword, persistAuth]);

  const register = useCallback(async () => {
    setRegisterBusy(true);
    setRegisterMessage(null);
    try {
      const res = await fetch("/api/users/register", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          email: registerEmail.trim(),
          password: registerPassword,
          fullName: registerFullName.trim(),
        }),
      });

      const body = (await res.json().catch(() => ({}))) as { userId?: string; error?: string };
      if (!res.ok || !body.userId) {
        throw new Error(body.error || "Registration failed.");
      }

      setRegisterMessage("Registration successful. You can now login.");
      setLoginEmail(registerEmail.trim());
      setLoginPassword(registerPassword);
      setRegisterEmail("");
      setRegisterPassword("");
      setRegisterFullName("");
    } catch (e) {
      setRegisterMessage(e instanceof Error ? e.message : "Registration failed");
    } finally {
      setRegisterBusy(false);
    }
  }, [registerEmail, registerFullName, registerPassword]);

  const loadProducts = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await authenticatedFetch("/api/products");
      if (!res.ok) {
        throw new Error(`Products failed: ${res.status}`);
      }
      const data: Product[] = await res.json();
      setProducts(data);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to load products");
    } finally {
      setLoading(false);
    }
  }, [authenticatedFetch]);

  useEffect(() => {
    void loadProducts();
  }, [loadProducts]);

  const persistCart = useCallback(async (items: CartItem[]) => {
    if (!currentUser?.userId) {
      throw new Error("Please login first.");
    }
    const res = await authenticatedFetch(`/api/carts/${currentUser.userId}`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ userId: currentUser.userId, items }),
    });
    if (!res.ok) {
      throw new Error(`Cart save failed: ${res.status}`);
    }
  }, [authenticatedFetch, currentUser?.userId]);

  const addToCart = useCallback(
    async (p: Product) => {
      setError(null);
      if (!currentUser?.userId) {
        setError("Please login first.");
        return;
      }
      const next = [...cart];
      const existing = next.find((x) => x.productId === p.productId);
      if (existing) {
        existing.quantity += 1;
      } else {
        next.push({ productId: p.productId, quantity: 1, unitPrice: p.price });
      }
      try {
        await persistCart(next);
        setCart(next);
      } catch (e) {
        setError(e instanceof Error ? e.message : "Cart error");
      }
    },
    [cart, currentUser?.userId, persistCart],
  );

  const checkout = useCallback(async () => {
    setCheckoutBusy(true);
    setCheckoutResult(null);
    setError(null);
    try {
      if (!currentUser?.userId || !authToken) {
        throw new Error("Please login first.");
      }
      if (cart.length === 0) {
        throw new Error("Cart is empty. Add a product first.");
      }

      const res = await authenticatedFetch("/api/checkout", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Idempotency-Key": newIdempotencyKey(),
        },
        body: JSON.stringify({
          userId: currentUser.userId,
          currency: "USD",
          items: cart.map((c) => ({
            productId: c.productId,
            quantity: c.quantity,
            unitPrice: c.unitPrice,
          })),
        }),
      });

      const body = await res.json().catch(() => ({}));
      if (!res.ok) {
        throw new Error(
          (body as { error?: string }).error ||
            `Checkout failed: ${res.status}`,
        );
      }

      setCheckoutResult(body);
      setCart([]);
      await loadProducts();
    } catch (e) {
      setError(e instanceof Error ? e.message : "Checkout error");
    } finally {
      setCheckoutBusy(false);
    }
  }, [authenticatedFetch, cart, currentUser?.userId, loadProducts]);

  const cartSummary = useMemo(
    () => cart.reduce((sum, c) => sum + c.quantity * c.unitPrice, 0),
    [cart],
  );

  return (
    <main>
      <h1>Online Store (React → HTTPS → Gateway)</h1>
      <p style={{ color: "#475569", marginTop: 0 }}>
        Demo user is pre-seeded in UserService. Cart is stored via CartService
        through the gateway so checkout validation matches the diagram.
      </p>

      {error ? <p className="error">{error}</p> : null}

      <section>
        <h2 style={{ marginTop: 0 }}>Login</h2>
        {loginMessage ? <p className="message">{loginMessage}</p> : null}
        <div className="form-grid">
          <label>
            Email
            <input type="email" value={loginEmail} onChange={(e) => setLoginEmail(e.target.value)} />
          </label>
          <label>
            Password
            <input type="password" value={loginPassword} onChange={(e) => setLoginPassword(e.target.value)} />
          </label>
          <div className="row-actions">
            <button type="button" disabled={loginBusy} onClick={() => void login()}>
              {loginBusy ? "Logging in..." : "Login"}
            </button>
            <button type="button" disabled={!authToken} onClick={logout}>
              Logout
            </button>
          </div>
        </div>
        {currentUser ? (
          <p>
            Logged in user: <strong>{currentUser.fullName}</strong> ({currentUser.email})
          </p>
        ) : null}
      </section>

      <section>
        <h2 style={{ marginTop: 0 }}>Register</h2>
        {registerMessage ? <p className="message">{registerMessage}</p> : null}
        <div className="form-grid">
          <label>
            Full name
            <input type="text" value={registerFullName} onChange={(e) => setRegisterFullName(e.target.value)} />
          </label>
          <label>
            Email
            <input type="email" value={registerEmail} onChange={(e) => setRegisterEmail(e.target.value)} />
          </label>
          <label>
            Password
            <input type="password" value={registerPassword} onChange={(e) => setRegisterPassword(e.target.value)} />
          </label>
          <div className="row-actions">
            <button type="button" disabled={registerBusy} onClick={() => void register()}>
              {registerBusy ? "Registering..." : "Register"}
            </button>
          </div>
        </div>
      </section>

      <section>
        <h2 style={{ marginTop: 0 }}>Catalog</h2>
        {loading ? (
          <p>Loading…</p>
        ) : (
          <ul>
            {products.map((p) => (
              <li key={p.productId}>
                <span>
                  <strong>{p.name}</strong> — ${p.price.toFixed(2)}
                </span>
                <button type="button" onClick={() => void addToCart(p)}>
                  Add to cart
                </button>
              </li>
            ))}
          </ul>
        )}
      </section>

      <section>
        <h2 style={{ marginTop: 0 }}>Cart</h2>
        {!authToken ? <p>Login required to persist cart and checkout.</p> : null}
        {cart.length === 0 ? (
          <p>Empty</p>
        ) : (
          <ul>
            {cart.map((c) => (
              <li key={c.productId}>
                <span>{c.productId}</span>
                <span>
                  qty {c.quantity} @ ${c.unitPrice.toFixed(2)}
                </span>
              </li>
            ))}
          </ul>
        )}
        <p>
          <strong>Total:</strong> ${cartSummary.toFixed(2)}
        </p>
        <button type="button" disabled={checkoutBusy} onClick={() => void checkout()}>
          {checkoutBusy ? "Checking out…" : "Checkout"}
        </button>
      </section>

      {checkoutResult ? (
        <section>
          <h2 style={{ marginTop: 0 }}>Last checkout</h2>
          <pre>{JSON.stringify(checkoutResult, null, 2)}</pre>
        </section>
      ) : null}
    </main>
  );
}
